### ISSUE TITLE
Usability tests

### ISSUE THREAD

**Issue by lauratbg** [Arquisoft/wiq_en1b#116]
Maybe do a form or something to have recorded the people (anonymous way) and some punctuation of the app

**Comment by lauratbg** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSelnlowMPz9pWrnuQmsoONGZSTJMQVCPne59MhupvXxVzk33g/viewform?usp=sf_link

**Comment by UO289845** [comment]
Responses to the form: https://docs.google.com/spreadsheets/d/1eP9VCuThp1RBwe5Zf5n2ol2vvN6_j0uY9txXErk0qqI/edit#gid=1442555861
