### ISSUE TITLE
PowerPoint of the presentation

### ISSUE THREAD

**Issue by lauratbg** [Arquisoft/wiq_en1b#118]

**Comment by UO289845** [comment]
# Redaction of the presentation
* Introduction and architechture (webapp & API) -> Mario
* Technologies (React, Java, MongoDB) -> Ahmet
* Application details: generator -> Jorge
* What makes our application unique? (x2) -> Laura & Daniel
* Monitoring & Tests (e2e, unitary, load, accesibility, usability) -> Lucía
