### ISSUE TITLE
Results from load tests

### ISSUE THREAD

**Issue by ErdemYabaci** [Arquisoft/wiq_en1b#149]

**Comment by UO289845** [comment]
I think it might be a good idea to have a big number of users in a very limited time, to test our application under some extra conditions.
Like (for example), let's say 100 users per second during 5 seconds.

**Comment by ErdemYabaci** [comment]
> I think it might be a good idea to have a big number of users in a very limited time, to test our application under some extra conditions. Like (for example), let's say 100 users per second during 5 seconds.

That's a good suggestion, will do.
