### ISSUE TITLE
Creating the protoypes of the UI

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#24]
Creating the protoypes of the User Interface. This might be done by:
- Sketches
- A Wireframe
- A MockUp
- Other

**Comment by lauratbg** [comment]
This can be an starting point maybe
![Uploading 1708945199461.jpg…]()

**Comment by uo289267** [comment]
![IMG20240226120009](https://github.com/Arquisoft/wiq_en1b/assets/124298009/eecdb665-4e97-4135-90af-63dcc3fb5e22)
![IMG20240226115952](https://github.com/Arquisoft/wiq_en1b/assets/124298009/ec72462f-f1ab-4052-ab06-f03e1ce05c66)

**Comment by lauratbg** [comment]
okey great!! can we mix your idea with the thing of the "help" and the "instructions"? I really like your points stuff though :)

**Comment by uo289267** [comment]
So we will add a question mark (?) in the nav menu so instructions can be checked at any point

**Comment by uo289267** [comment]
Laura: Home View, Login View, Register new Account
Lucia: Game Configuration, Questions

**Comment by uo289267** [comment]
_Change of View Plans_
The Game configuration is a optional requirement so I suggest the following new view for after the user has login or registered succesfully


![Image](https://github.com/Arquisoft/wiq_en1b/assets/124298009/4a60b6c4-794a-48de-9c91-d0d28d6276da)

The Games' History button will allow the user to view its historial data from previous games (And I will implement this but maybe in the next prototype)
The New Game will start a new game with the view 'PREGUNTAS' presented previously

**Comment by uo289267** [comment]
Yes, do you agree or have a different view?

**Comment by lauratbg** [comment]
Yes yes, I agree of course!
