### ISSUE TITLE
Jorge's Self Report - Second Deliverable

### ISSUE THREAD

**Issue by lauratbg** [Arquisoft/wiq_en1b#39]

**Comment by UO289845** [comment]
For the first prototype I started by finishing the Documentation Part 1, as detailed by the teacher. 
* #3 
* #25 

Apart from that, my work has mostly lied in the implementation of the Question Generation. While the testing and the wrong answers weren¡t done by me, I worked on the main logic of the generation, creating questions and the correct answers.
* #22 
* #23 
* #30 
* #36 
* #44 
* #47 

I've also taken the following minutes:
* [Eighth-meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Eighth-Meeting)

And finally, I have participated in the following minutes:
* [Fifth-meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Fifth-Meeting)
* [Sixth-meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Sixth-Minute)
* [Seventh-meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Seventh-Meeting)
