### ISSUE TITLE
03-System Scope and Context

### ISSUE THREAD

**Issue by Mister-Mario** [Arquisoft/wiq_en1b#5]
Assigment of the System Scope and Context topic in the documentation

**Comment by uo289267** [comment]
- Technical Context ->protocol to communicate wikidata and question generation microservice , remove db to be inside 
- Business Context ->separate wiq in different microservices (user auth.->backend, wikidata question generation)

**Comment by uo289267** [comment]
- Comunication in the technical context with wikidata
