### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by Mister-Mario** [Arquisoft/wiq_en1b#62]
Create an endpoint to save a game played by an user and being able to retrieve it later

**Comment by uo289267** [comment]
![image](https://github.com/Arquisoft/wiq_en1b/assets/124298009/2d03d5c1-29e9-4c1e-92d2-55e06d900f25)
View of historical Data

**Comment by uo289267** [comment]
![image](https://github.com/Arquisoft/wiq_en1b/assets/124298009/40f5bf84-5f50-47d3-9f46-c79d904971e4)
View of one of the games stored in the historical data

**Comment by Mister-Mario** [comment]
//DB
{
  "userIdentification": "prob email or username",
  "games": [
    {
      "questions": [
        {
          "question": "¿Cuál es la capital de Francia?",
          "answers": ["Madrid", "París", "Londres", "Roma"],
          "answerGiven": "París",
          "correctAnswer": "París"
        },
        {
          "question": "¿En qué año comenzó la Segunda Guerra Mundial?",
          "answers": ["1939", "1945", "1914", "1941"],
          "answerGiven": "1939",
          "correctAnswer": "1939"
        },
        {
          "question": "¿Quién escribió 'Don Quijote de la Mancha'?",
          "answers": ["Miguel de Cervantes", "Gabriel García Márquez", "Federico García Lorca", "Jorge Luis Borges"],
          "answerGiven": "Miguel de Cervantes",
          "correctAnswer": "Miguel de Cervantes"
        }
      ],
      "points": 3000,
      "date": "01/02/24"
    },
    {
      "questions": [
        {
          "question": "¿Cuál es el río más largo del mundo?",
          "answers": ["Nilo", "Amazonas", "Yangtsé", "Misisipi"],
          "answerGiven": "Amazonas",
          "correctAnswer": "Amazonas"
        },
        {
          "question": "¿Cuál es el elemento más abundante en la corteza terrestre?",
          "answers": ["Hierro", "Oxígeno", "Silicio", "Aluminio"],
          "answerGiven": "Oxígeno",
          "correctAnswer": "Oxígeno"
        }
      ],
      "points": 2500,
      "date": "02/02/24"
    },
    {
      "questions": [
        {
          "question": "¿Quién pintó la Mona Lisa?",
          "answers": ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Rembrandt"],
          "answerGiven": "Leonardo da Vinci",
          "correctAnswer": "Leonardo da Vinci"
        },
        {
          "question": "¿Cuál es el planeta más grande del sistema solar?",
          "answers": ["Júpiter", "Saturno", "Neptuno", "Urano"],
          "answerGiven": "Júpiter",
          "correctAnswer": "Júpiter"
        }
      ],
      "points": 3500,
      "date": "03/02/24"
    }
  ]
}
