### ISSUE TITLE
Jest Tests FrontEnd

### ISSUE THREAD

**Issue by uo289267** [Arquisoft/wiq_en1b#66]
Creation of tests for all React components

**Comment by uo289267** [comment]
import { render, screen } from '@testing-library/react';
import GameMenu from './GameMenu';
import { MemoryRouter } from 'react-router-dom';


test('renders learn react link', () => {
  render(<MemoryRouter><GameMenu /></MemoryRouter>);
  //const linkElement = screen.getByText(/Welcome to the 2024 edition of the Software Architecture course/i);
  //expect(linkElement).toBeInTheDocument();
});

**Comment by lauratbg** [comment]
![image](https://github.com/Arquisoft/wiq_en1b/assets/78926547/008ae414-db29-4dc6-a9e5-31b01b65ec33)
This warning appears, we should find a solution

**Comment by lauratbg** [comment]
That warning is solved adding the following code to setuptests.js
![image](https://github.com/Arquisoft/wiq_en1b/assets/78926547/064483d4-9b7e-41bc-ad26-c03cb76d89cf)
