### ISSUE TITLE
Mario's Self Report - Third Deliverable

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#73]

**Comment by Mister-Mario** [comment]
My work was based on doing improvements to the documentation:
* [Updating documentation](https://github.com/Arquisoft/wiq_en1b/tree/Updating-doc)
And to the backend, new services and tests:
*  #56
*  #59
*  #62 
And make them work with the webapp, modifying source code and helping with tests:
* #69 
Also merged everything as commits show with help of Lucía
* [master](https://github.com/Arquisoft/wiq_en1b/tree/master)
And made the release v0.1
* [v0.1](https://github.com/Arquisoft/wiq_en1b/tree/v0.1)

Finally, I have taken part in the following minutes:
* [Ninth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Ninth%E2%80%90Meeting)
* [Tenth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Tenth%E2%80%90Meeting) 
* [Eleventh Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Eleventh-Meeting)
* [Twelfth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Twelfth-Meeting)
