### ISSUE TITLE
Lucía's Self Report - Third Deliverable

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#74]

**Comment by uo289267** [comment]
My work has been improving front-end visualization, new Historical View and saving the records after playing a game. Finally small changes for the README configurations of the project. Moreover, jest tests for Historical View, Question View and the rest of my components.
This is reflected in the following issues:

- https://github.com/Arquisoft/wiq_en1b/issues/54
- https://github.com/Arquisoft/wiq_en1b/issues/62
- https://github.com/Arquisoft/wiq_en1b/issues/66
And I've worked in the branches:

- [Front end development + testing](https://github.com/Arquisoft/wiq_en1b/tree/front-end-lucia)
- [README changes](https://github.com/Arquisoft/wiq_en1b/tree/69-making-the-webapp-use-the-record-service-through-the-gateway-service)

I also supervised the final deployment of the application.

Finally, I have taken part in the following minutes:

- [Ninth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Ninth%E2%80%90Meeting)
- [Tenth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Tenth%E2%80%90Meeting)
- The one that I took: [Eleventh Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Eleventh-Meeting)
- [Twelfth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Twelfth-Meeting)
