### ISSUE TITLE
Laura's Self Report - Third Deliverable

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#75]

**Comment by lauratbg** [comment]
My work was based on doing improvements of the frontend and also do tests. This is reflected in the following issues:
*  #54 
*  #66 

And I've worked in the branches:
* [Front end improvements](https://github.com/Arquisoft/wiq_en1b/tree/frontend-laura)
* [Jest testing](https://github.com/Arquisoft/wiq_en1b/tree/jest-Laura)
* [e2e tests](https://github.com/Arquisoft/wiq_en1b/tree/e2e)


Finally, I have taken part in the following minutes:
* [Ninth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Ninth%E2%80%90Meeting)
* The one that I took: [Tenth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Tenth%E2%80%90Meeting) 
* [Eleventh Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Eleventh-Meeting)
* [Twelfth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Twelfth-Meeting)
