### ISSUE TITLE
Daniel's Self Report - Third Deliverable

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#77]

**Comment by sinne10** [comment]
For the third delivery, I did work related with the improvement of the backend and the finishing of the documentation.
Issues I was a part of:
* #57 
* #60 
* #79 

And I've worked in the branches:
* [60-add-questions-more-efficiently-to-database](https://github.com/Arquisoft/wiq_en1b/tree/60-add-questions-more-efficiently-to-database)
* [Updating-doc](https://github.com/Arquisoft/wiq_en1b/tree/Updating-doc)

Also, I have participated in the pull requests:
* #80
* #63 

Finally, I have taken part in the following minutes:
* [Ninth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Ninth%E2%80%90Meeting)
* [Tenth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Tenth%E2%80%90Meeting)
* [Eleventh-Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Eleventh-Meeting)
* [Twelfth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Twelfth-Meeting)
