### ISSUE TITLE
User policies

### ISSUE THREAD

**Issue by sinne10** [Arquisoft/wiq_en1b#90]
Design and implement user policies

**Comment by sinne10** [comment]
Some ideas for registration policies:

- Username policies:
&emsp;Should not include spaces
&emsp;Should not be in use

- Email policies:
&emsp;Syntax check (https://stackoverflow.com/questions/46155/how-can-i-validate-an-email-address-in-javascript)
&emsp;Should not be in use

- Password policies:
&emsp;No spaces
&emsp;Minimum length of 8 characters
&emsp;Maximum length of 64 characters
&emsp;Password strength meter using zxcvbn (https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation)

**Comment by Mister-Mario** [comment]
I like the idea of using a password strenght meter, could you try to find some module for React for doing it so it is easier for the front-end team to implement it

**Comment by sinne10** [comment]
I will look for one. However, I have implemented it in this issue's branch with a progress bar.
See [90-user-policies](https://github.com/Arquisoft/wiq_en1b/tree/90-user-policies)

**Comment by Mister-Mario** [comment]
Oh that's fantastic, do a pull request whenever you are ready
