### ISSUE TITLE
Ranking for Players

### ISSUE THREAD

**Issue by uo289267** [Arquisoft/wiq_en1b#97]
![image](https://github.com/Arquisoft/wiq_en1b/assets/124298009/72e31790-d068-41a0-bc39-7ba18854e667)

**Comment by Mister-Mario** [comment]
2 endpoints:

record/ranking/top10 will get the top10 users returning inside the body a json object called usersCompetitiveStats that has an array of lenght 10 where each item follows this schema
           {
              _id: "user",
              totalPoints: 100,
              totalCompetitiveGames: 2
          }
          
record/ranking/:user will return a json under userCompetitiveStats with the same schema as above but for just one user

**Comment by uo289267** [comment]
So an example of a top 10 ranking would be
``` java

{
  "usersCompetitiveStats": [
    {
      "_id": "user",
      "totalPoints": 1000,
      "totalCompetitiveGames": 4
    },
    {
      "_id": "user2",
      "totalPoints": 900,
      "totalCompetitiveGames": 2
    },
    {
      "_id": "user3",
      "totalPoints": 800,
      "totalCompetitiveGames": 3
    },
    {
      "_id": "user4",
      "totalPoints": 700,
      "totalCompetitiveGames": 5
    },
    {
      "_id": "user5",
      "totalPoints": 600,
      "totalCompetitiveGames": 6
    },
    {
      "_id": "user6",
      "totalPoints": 500,
      "totalCompetitiveGames": 7
    },
    {
      "_id": "user7",
      "totalPoints": 400,
      "totalCompetitiveGames": 8
    },
    {
      "_id": "user8",
      "totalPoints": 300,
      "totalCompetitiveGames": 9
    },
    {
      "_id": "user9",
      "totalPoints": 200,
      "totalCompetitiveGames": 10
    },
    {
      "_id": "user10",
      "totalPoints": 100,
      "totalCompetitiveGames": 11
    }
  ]
}
´´´

**Comment by uo289267** [comment]
Okay with the info provided for a single user I cannot tell in which position they are in, because with the top ten you have guaranteed me that the array inside the json is ordered from the first (with position 1) to the last (with position 10) however when giving me a single record with id of the person, total number of points and totalCompetitive games I am not able to fill their position in the table

**Comment by Mister-Mario** [comment]
The json for each individual has being modified by adding a new field position
{_id , totalPoints, totalCompetitiveGames, position}
